import { Alphabet, Word, AForApple } from './types';

export const ALPHABETS: Alphabet[] = [
  { id: 'a', letter: 'A (a)', hindiPronunciation: 'ए', emoji: '🍎' },
  { id: 'b', letter: 'B (b)', hindiPronunciation: 'बी', emoji: '⚽' },
  { id: 'c', letter: 'C (c)', hindiPronunciation: 'सी', emoji: '🐱' },
  { id: 'd', letter: 'D (d)', hindiPronunciation: 'डी', emoji: '🐶' },
  { id: 'e', letter: 'E (e)', hindiPronunciation: 'ई', emoji: '🐘' },
  { id: 'f', letter: 'F (f)', hindiPronunciation: 'एफ', emoji: '🐸' },
  { id: 'g', letter: 'G (g)', hindiPronunciation: 'जी', emoji: '🐐' },
  { id: 'h', letter: 'H (h)', hindiPronunciation: 'एच', emoji: '🐴' },
  { id: 'i', letter: 'I (i)', hindiPronunciation: 'आई', emoji: '🍦' },
  { id: 'j', letter: 'J (j)', hindiPronunciation: 'जे', emoji: '🧃' },
  { id: 'k', letter: 'K (k)', hindiPronunciation: 'के', emoji: '🪁' },
  { id: 'l', letter: 'L (l)', hindiPronunciation: 'एल', emoji: '🦁' },
  { id: 'm', letter: 'M (m)', hindiPronunciation: 'एम', emoji: '🐒' },
  { id: 'n', letter: 'N (n)', hindiPronunciation: 'एन', emoji: '🪹' },
  { id: 'o', letter: 'O (o)', hindiPronunciation: 'ओ', emoji: '🦉' },
  { id: 'p', letter: 'P (p)', hindiPronunciation: 'पी', emoji: '🦚' },
  { id: 'q', letter: 'Q (q)', hindiPronunciation: 'क्यू', emoji: '👑' },
  { id: 'r', letter: 'R (r)', hindiPronunciation: 'आर', emoji: '🌹' },
  { id: 's', letter: 'S (s)', hindiPronunciation: 'एस', emoji: '🌞' },
  { id: 't', letter: 'T (t)', hindiPronunciation: 'टी', emoji: '🐅' },
  { id: 'u', letter: 'U (u)', hindiPronunciation: 'यू', emoji: '☂️' },
  { id: 'v', letter: 'V (v)', hindiPronunciation: 'वी', emoji: '🚐' },
  { id: 'w', letter: 'W (w)', hindiPronunciation: 'डब्लू', emoji: '⌚' },
  { id: 'x', letter: 'X (x)', hindiPronunciation: 'एक्स', emoji: '🎼' },
  { id: 'y', letter: 'Y (y)', hindiPronunciation: 'वाय', emoji: '🛥️' },
  { id: 'z', letter: 'Z (z)', hindiPronunciation: 'ज़ेड', emoji: '🦓' },
];

export const A_FOR_APPLE: AForApple[] = [
  { id: 'a', letter: 'A (a)', word: 'Apple', hindiPronunciation: 'ए', hindiTransliteration: 'एप्पल', hindiMeaning: 'सेब', emoji: '🍎' },
  { id: 'b', letter: 'B (b)', word: 'Ball', hindiPronunciation: 'बी', hindiTransliteration: 'बॉल', hindiMeaning: 'गेंद', emoji: '⚽' },
  { id: 'c', letter: 'C (c)', word: 'Cat', hindiPronunciation: 'सी', hindiTransliteration: 'कैट', hindiMeaning: 'बिल्ली', emoji: '🐱' },
  { id: 'd', letter: 'D (d)', word: 'Dog', hindiPronunciation: 'डी', hindiTransliteration: 'डॉग', hindiMeaning: 'कुत्ता', emoji: '🐶' },
  { id: 'e', letter: 'E (e)', word: 'Elephant', hindiPronunciation: 'ई', hindiTransliteration: 'एलिफेंट', hindiMeaning: 'हाथी', emoji: '🐘' },
  { id: 'f', letter: 'F (f)', word: 'Frog', hindiPronunciation: 'एफ', hindiTransliteration: 'फ्रॉग', hindiMeaning: 'मेंढक', emoji: '🐸' },
  { id: 'g', letter: 'G (g)', word: 'Goat', hindiPronunciation: 'जी', hindiTransliteration: 'गोट', hindiMeaning: 'बकरी', emoji: '🐐' },
  { id: 'h', letter: 'H (h)', word: 'Horse', hindiPronunciation: 'एच', hindiTransliteration: 'हॉर्स', hindiMeaning: 'घोड़ा', emoji: '🐴' },
  { id: 'i', letter: 'I (i)', word: 'Ice Cream', hindiPronunciation: 'आई', hindiTransliteration: 'आइस क्रीम', hindiMeaning: 'आइस क्रीम', emoji: '🍦' },
  { id: 'j', letter: 'J (j)', word: 'Juice', hindiPronunciation: 'जे', hindiTransliteration: 'जूस', hindiMeaning: 'रस', emoji: '🧃' },
  { id: 'k', letter: 'K (k)', word: 'Kite', hindiPronunciation: 'के', hindiTransliteration: 'काइट', hindiMeaning: 'पतंग', emoji: '🪁' },
  { id: 'l', letter: 'L (l)', word: 'Lion', hindiPronunciation: 'एल', hindiTransliteration: 'लायन', hindiMeaning: 'शेर', emoji: '🦁' },
  { id: 'm', letter: 'M (m)', word: 'Monkey', hindiPronunciation: 'एम', hindiTransliteration: 'मंकी', hindiMeaning: 'बंदर', emoji: '🐒' },
  { id: 'n', letter: 'N (n)', word: 'Nest', hindiPronunciation: 'एन', hindiTransliteration: 'नेस्ट', hindiMeaning: 'घोंसला', emoji: '🪹' },
  { id: 'o', letter: 'O (o)', word: 'Owl', hindiPronunciation: 'ओ', hindiTransliteration: 'आउल', hindiMeaning: 'उल्लू', emoji: '🦉' },
  { id: 'p', letter: 'P (p)', word: 'Peacock', hindiPronunciation: 'पी', hindiTransliteration: 'पीकॉक', hindiMeaning: 'मोर', emoji: '🦚' },
  { id: 'q', letter: 'Q (q)', word: 'Queen', hindiPronunciation: 'क्यू', hindiTransliteration: 'क्वीन', hindiMeaning: 'रानी', emoji: '👑' },
  { id: 'r', letter: 'R (r)', word: 'Rose', hindiPronunciation: 'आर', hindiTransliteration: 'रोज़', hindiMeaning: 'गुलाब', emoji: '🌹' },
  { id: 's', letter: 'S (s)', word: 'Sun', hindiPronunciation: 'एस', hindiTransliteration: 'सन', hindiMeaning: 'सूरज', emoji: '🌞' },
  { id: 't', letter: 'T (t)', word: 'Tiger', hindiPronunciation: 'टी', hindiTransliteration: 'टाइगर', hindiMeaning: 'बाघ', emoji: '🐅' },
  { id: 'u', letter: 'U (u)', word: 'Umbrella', hindiPronunciation: 'यू', hindiTransliteration: 'अम्ब्रेला', hindiMeaning: 'छाता', emoji: '☂️' },
  { id: 'v', letter: 'V (v)', word: 'Van', hindiPronunciation: 'वी', hindiTransliteration: 'वैन', hindiMeaning: 'गाड़ी', emoji: '🚐' },
  { id: 'w', letter: 'W (w)', word: 'Watch', hindiPronunciation: 'डब्लू', hindiTransliteration: 'वॉच', hindiMeaning: 'घड़ी', emoji: '⌚' },
  { id: 'x', letter: 'X (x)', word: 'Xylophone', hindiPronunciation: 'एक्स', hindiTransliteration: 'ज़ाइलोफोन', hindiMeaning: 'जलतरंग', emoji: '🎼' },
  { id: 'y', letter: 'Y (y)', word: 'Yacht', hindiPronunciation: 'वाय', hindiTransliteration: 'यॉट', hindiMeaning: 'नाव', emoji: '🛥️' },
  { id: 'z', letter: 'Z (z)', word: 'Zebra', hindiPronunciation: 'ज़ेड', hindiTransliteration: 'ज़ेबरा', hindiMeaning: 'ज़ेबरा', emoji: '🦓' },
];

export const WORDS: Word[] = [
  { id: 'w1', englishWord: 'Apple', hindiTransliteration: 'एप्पल', hindiMeaning: 'सेब', emoji: '🍎' },
  { id: 'w2', englishWord: 'Water', hindiTransliteration: 'वाटर', hindiMeaning: 'पानी', emoji: '💧' },
  { id: 'w3', englishWord: 'Book', hindiTransliteration: 'बुक', hindiMeaning: 'किताब', emoji: '📖' },
  { id: 'w4', englishWord: 'Sun', hindiTransliteration: 'सन', hindiMeaning: 'सूरज', emoji: '☀️' },
  { id: 'w5', englishWord: 'Home', hindiTransliteration: 'होम', hindiMeaning: 'घर', emoji: '🏠' },
  { id: 'w6', englishWord: 'Dog', hindiTransliteration: 'डॉग', hindiMeaning: 'कुत्ता', emoji: '🐶' },
  { id: 'w7', englishWord: 'Cat', hindiTransliteration: 'कैट', hindiMeaning: 'बिल्ली', emoji: '🐱' },
  { id: 'w8', englishWord: 'Moon', hindiTransliteration: 'मून', hindiMeaning: 'चाँद', emoji: '🌙' },
  { id: 'w9', englishWord: 'Tree', hindiTransliteration: 'ट्री', hindiMeaning: 'पेड़', emoji: '🌳' },
  { id: 'w10', englishWord: 'Milk', hindiTransliteration: 'मिल्क', hindiMeaning: 'दूध', emoji: '🥛' },
  // Adding 100 common words
  { id: 'w11', englishWord: 'Father', hindiTransliteration: 'फादर', hindiMeaning: 'पिता', emoji: '👨' },
  { id: 'w12', englishWord: 'Mother', hindiTransliteration: 'मदर', hindiMeaning: 'माँ', emoji: '👩' },
  { id: 'w13', englishWord: 'Food', hindiTransliteration: 'फ़ूड', hindiMeaning: 'खाना', emoji: '🍛' },
  { id: 'w14', englishWord: 'Sleep', hindiTransliteration: 'स्लीप', hindiMeaning: 'सोना', emoji: '😴' },
  { id: 'w15', englishWord: 'Eat', hindiTransliteration: 'ईट', hindiMeaning: 'खाना', emoji: '🍽️' },
  { id: 'w16', englishWord: 'Drink', hindiTransliteration: 'ड्रिंक', hindiMeaning: 'पीना', emoji: '🥤' },
  { id: 'w17', englishWord: 'Come', hindiTransliteration: 'कम', hindiMeaning: 'आना', emoji: '🏃' },
  { id: 'w18', englishWord: 'Go', hindiTransliteration: 'गो', hindiMeaning: 'जाना', emoji: '🚶' },
  { id: 'w19', englishWord: 'Yes', hindiTransliteration: 'यस', hindiMeaning: 'हाँ', emoji: '👍' },
  { id: 'w20', englishWord: 'No', hindiTransliteration: 'नो', hindiMeaning: 'नहीं', emoji: '👎' },
  { id: 'w21', englishWord: 'Good', hindiTransliteration: 'गुड', hindiMeaning: 'अच्छा', emoji: '😊' },
  { id: 'w22', englishWord: 'Bad', hindiTransliteration: 'बैड', hindiMeaning: 'खराब', emoji: '☹️' },
  { id: 'w23', englishWord: 'Big', hindiTransliteration: 'बिग', hindiMeaning: 'बड़ा', emoji: '🐘' },
  { id: 'w24', englishWord: 'Small', hindiTransliteration: 'स्मॉल', hindiMeaning: 'छोटा', emoji: '🐁' },
  { id: 'w25', englishWord: 'Hot', hindiTransliteration: 'हॉट', hindiMeaning: 'गर्म', emoji: '🔥' },
  { id: 'w26', englishWord: 'Cold', hindiTransliteration: 'कोल्ड', hindiMeaning: 'ठंडा', emoji: '❄️' },
  { id: 'w27', englishWord: 'Day', hindiTransliteration: 'डे', hindiMeaning: 'दिन', emoji: '🌞' },
  { id: 'w28', englishWord: 'Night', hindiTransliteration: 'नाईट', hindiMeaning: 'रात', emoji: '🌃' },
  { id: 'w29', englishWord: 'Morning', hindiTransliteration: 'मॉर्निंग', hindiMeaning: 'सुबह', emoji: '🌅' },
  { id: 'w30', englishWord: 'Evening', hindiTransliteration: 'ईवनिंग', hindiMeaning: 'शाम', emoji: '🌇' },
  { id: 'w31', englishWord: 'Boy', hindiTransliteration: 'बॉय', hindiMeaning: 'लड़का', emoji: '👦' },
  { id: 'w32', englishWord: 'Girl', hindiTransliteration: 'गर्ल', hindiMeaning: 'लड़की', emoji: '👧' },
  { id: 'w33', englishWord: 'Man', hindiTransliteration: 'मैन', hindiMeaning: 'आदमी', emoji: '👨' },
  { id: 'w34', englishWord: 'Woman', hindiTransliteration: 'वुमन', hindiMeaning: 'महिला', emoji: '👩' },
  { id: 'w35', englishWord: 'Pen', hindiTransliteration: 'पेन', hindiMeaning: 'कलम', emoji: '🖊️' },
  { id: 'w36', englishWord: 'Star', hindiTransliteration: 'स्टार', hindiMeaning: 'तारा', emoji: '⭐' },
  { id: 'w37', englishWord: 'Sky', hindiTransliteration: 'स्काई', hindiMeaning: 'आसमान', emoji: '🌌' },
  { id: 'w38', englishWord: 'Leaf', hindiTransliteration: 'लीफ', hindiMeaning: 'पत्ता', emoji: '🍂' },
  { id: 'w39', englishWord: 'Hand', hindiTransliteration: 'हैंड', hindiMeaning: 'हाथ', emoji: '✋' },
  { id: 'w40', englishWord: 'Foot', hindiTransliteration: 'फुट', hindiMeaning: 'पैर', emoji: '🦶' },
  { id: 'w41', englishWord: 'Eye', hindiTransliteration: 'आई', hindiMeaning: 'आँख', emoji: '👁️' },
  { id: 'w42', englishWord: 'Ear', hindiTransliteration: 'इयर', hindiMeaning: 'कान', emoji: '👂' },
  { id: 'w43', englishWord: 'Nose', hindiTransliteration: 'नोज़', hindiMeaning: 'नाक', emoji: '👃' },
  { id: 'w44', englishWord: 'Mouth', hindiTransliteration: 'माउथ', hindiMeaning: 'मुँह', emoji: '👄' },
  { id: 'w45', englishWord: 'Hair', hindiTransliteration: 'हेयर', hindiMeaning: 'बाल', emoji: '💇' },
  { id: 'w46', englishWord: 'Head', hindiTransliteration: 'हेड', hindiMeaning: 'सिर', emoji: '🗣️' },
  { id: 'w47', englishWord: 'Face', hindiTransliteration: 'फेस', hindiMeaning: 'चेहरा', emoji: '😀' },
  { id: 'w48', englishWord: 'Heart', hindiTransliteration: 'हार्ट', hindiMeaning: 'दिल', emoji: '❤️' },
  { id: 'w49', englishWord: 'Love', hindiTransliteration: 'लव', hindiMeaning: 'प्यार', emoji: '💕' },
  { id: 'w50', englishWord: 'Friend', hindiTransliteration: 'फ्रेंड', hindiMeaning: 'दोस्त', emoji: '🤝' },
  { id: 'w51', englishWord: 'Happy', hindiTransliteration: 'हैप्पी', hindiMeaning: 'खुश', emoji: '😄' },
  { id: 'w52', englishWord: 'Sad', hindiTransliteration: 'सैड', hindiMeaning: 'उदास', emoji: '😢' },
  { id: 'w53', englishWord: 'Angry', hindiTransliteration: 'एंग्री', hindiMeaning: 'गुस्सा', emoji: '😠' },
  { id: 'w54', englishWord: 'Slow', hindiTransliteration: 'स्लो', hindiMeaning: 'धीरे', emoji: '🐢' },
  { id: 'w55', englishWord: 'Fast', hindiTransliteration: 'फ़ास्ट', hindiMeaning: 'तेज़', emoji: '🚀' },
  { id: 'w56', englishWord: 'Up', hindiTransliteration: 'अप', hindiMeaning: 'ऊपर', emoji: '⬆️' },
  { id: 'w57', englishWord: 'Down', hindiTransliteration: 'डाउन', hindiMeaning: 'नीचे', emoji: '⬇️' },
  { id: 'w58', englishWord: 'Left', hindiTransliteration: 'लेफ्ट', hindiMeaning: 'बायां', emoji: '⬅️' },
  { id: 'w59', englishWord: 'Right', hindiTransliteration: 'राईट', hindiMeaning: 'दायां', emoji: '➡️' },
  { id: 'w60', englishWord: 'Near', hindiTransliteration: 'नियर', hindiMeaning: 'पास', emoji: '📍' },
  { id: 'w61', englishWord: 'Far', hindiTransliteration: 'फार', hindiMeaning: 'दूर', emoji: '🔭' },
  { id: 'w62', englishWord: 'Open', hindiTransliteration: 'ओपन', hindiMeaning: 'खोलना', emoji: '📖' },
  { id: 'w63', englishWord: 'Close', hindiTransliteration: 'क्लोज़', hindiMeaning: 'बंद करना', emoji: '📕' },
  { id: 'w64', englishWord: 'Door', hindiTransliteration: 'डोर', hindiMeaning: 'दरवाज़ा', emoji: '🚪' },
  { id: 'w65', englishWord: 'Window', hindiTransliteration: 'विंडो', hindiMeaning: 'खिड़की', emoji: '🪟' },
  { id: 'w66', englishWord: 'Table', hindiTransliteration: 'टेबल', hindiMeaning: 'मेज़', emoji: '🪑' },
  { id: 'w67', englishWord: 'Chair', hindiTransliteration: 'चेयर', hindiMeaning: 'कुर्सी', emoji: '💺' },
  { id: 'w68', englishWord: 'Bed', hindiTransliteration: 'बेड', hindiMeaning: 'बिस्तर', emoji: '🛏️' },
  { id: 'w69', englishWord: 'Room', hindiTransliteration: 'रूम', hindiMeaning: 'कमरा', emoji: '🛋️' },
  { id: 'w70', englishWord: 'Car', hindiTransliteration: 'कार', hindiMeaning: 'गाड़ी', emoji: '🚗' },
  { id: 'w71', englishWord: 'Bus', hindiTransliteration: 'बस', hindiMeaning: 'बस', emoji: '🚌' },
  { id: 'w72', englishWord: 'Train', hindiTransliteration: 'ट्रेन', hindiMeaning: 'रेलगाड़ी', emoji: '🚆' },
  { id: 'w73', englishWord: 'Road', hindiTransliteration: 'रोड', hindiMeaning: 'सड़क', emoji: '🛣️' },
  { id: 'w74', englishWord: 'Money', hindiTransliteration: 'मनी', hindiMeaning: 'पैसा', emoji: '💰' },
  { id: 'w75', englishWord: 'Shop', hindiTransliteration: 'शॉप', hindiMeaning: 'दुकान', emoji: '🏪' },
  { id: 'w76', englishWord: 'Buy', hindiTransliteration: 'बाय', hindiMeaning: 'खरीदना', emoji: '🛍️' },
  { id: 'w77', englishWord: 'Sell', hindiTransliteration: 'सेल', hindiMeaning: 'बेचना', emoji: '🏷️' },
  { id: 'w78', englishWord: 'Give', hindiTransliteration: 'गिव', hindiMeaning: 'देना', emoji: '🎁' },
  { id: 'w79', englishWord: 'Take', hindiTransliteration: 'टेक', hindiMeaning: 'लेना', emoji: '🤲' },
  { id: 'w80', englishWord: 'See', hindiTransliteration: 'सी', hindiMeaning: 'देखना', emoji: '👀' },
  { id: 'w81', englishWord: 'Hear', hindiTransliteration: 'हियर', hindiMeaning: 'सुनना', emoji: '👂' },
  { id: 'w82', englishWord: 'Speak', hindiTransliteration: 'स्पीक', hindiMeaning: 'बोलना', emoji: '🗣️' },
  { id: 'w83', englishWord: 'Read', hindiTransliteration: 'रीड', hindiMeaning: 'पढ़ना', emoji: '📚' },
  { id: 'w84', englishWord: 'Write', hindiTransliteration: 'राईट', hindiMeaning: 'लिखना', emoji: '✍️' },
  { id: 'w85', englishWord: 'Walk', hindiTransliteration: 'वॉक', hindiMeaning: 'चलना', emoji: '🚶' },
  { id: 'w86', englishWord: 'Run', hindiTransliteration: 'रन', hindiMeaning: 'दौड़ना', emoji: '🏃' },
  { id: 'w87', englishWord: 'Work', hindiTransliteration: 'वर्क', hindiMeaning: 'काम', emoji: '💼' },
  { id: 'w88', englishWord: 'Play', hindiTransliteration: 'प्ले', hindiMeaning: 'खेलना', emoji: '🎮' },
  { id: 'w89', englishWord: 'Help', hindiTransliteration: 'हेल्प', hindiMeaning: 'मदद', emoji: '🆘' },
  { id: 'w90', englishWord: 'Stop', hindiTransliteration: 'स्टॉप', hindiMeaning: 'रुकना', emoji: '🛑' },
  { id: 'w91', englishWord: 'Wait', hindiTransliteration: 'वेट', hindiMeaning: 'इंतज़ार', emoji: '⏳' },
  { id: 'w92', englishWord: 'Today', hindiTransliteration: 'टुडे', hindiMeaning: 'आज', emoji: '📅' },
  { id: 'w93', englishWord: 'Tomorrow', hindiTransliteration: 'टुमॉरो', hindiMeaning: 'आने वाला कल', emoji: '📆' },
  { id: 'w94', englishWord: 'Yesterday', hindiTransliteration: 'यस्टरडे', hindiMeaning: 'बीता हुआ कल', emoji: '🗓️' },
  { id: 'w95', englishWord: 'Week', hindiTransliteration: 'वीक', hindiMeaning: 'सप्ताह', emoji: '🗓️' },
  { id: 'w96', englishWord: 'Month', hindiTransliteration: 'मंथ', hindiMeaning: 'महीना', emoji: '🌙' },
  { id: 'w97', englishWord: 'Year', hindiTransliteration: 'इयर', hindiMeaning: 'साल', emoji: '🎄' },
  { id: 'w98', englishWord: 'Time', hindiTransliteration: 'टाइम', hindiMeaning: 'समय', emoji: '⏱️' },
  { id: 'w99', englishWord: 'Hour', hindiTransliteration: 'आवर', hindiMeaning: 'घंटा', emoji: '⌛' },
  { id: 'w100', englishWord: 'Minute', hindiTransliteration: 'मिनट', hindiMeaning: 'मिनट', emoji: '⌚' },
  { id: 'w101', englishWord: 'Paper', hindiTransliteration: 'पेपर', hindiMeaning: 'कागज', emoji: '📄' },
  { id: 'w102', englishWord: 'School', hindiTransliteration: 'स्कूल', hindiMeaning: 'विद्यालय', emoji: '🏫' },
  { id: 'w103', englishWord: 'Teacher', hindiTransliteration: 'टीचर', hindiMeaning: 'अध्यापक', emoji: '🧑‍🏫' },
  { id: 'w104', englishWord: 'Student', hindiTransliteration: 'स्टूडेंट', hindiMeaning: 'विद्यार्थी', emoji: '🧑‍🎓' },
  { id: 'w105', englishWord: 'Doctor', hindiTransliteration: 'डॉक्टर', hindiMeaning: 'चिकित्सक', emoji: '👨‍⚕️' },
  { id: 'w106', englishWord: 'Hospital', hindiTransliteration: 'हॉस्पिटल', hindiMeaning: 'अस्पताल', emoji: '🏥' },
  { id: 'w107', englishWord: 'Medicine', hindiTransliteration: 'मेडिसिन', hindiMeaning: 'दवा', emoji: '💊' },
  { id: 'w108', englishWord: 'Phone', hindiTransliteration: 'फ़ोन', hindiMeaning: 'फ़ोन', emoji: '📱' },
  { id: 'w109', englishWord: 'City', hindiTransliteration: 'सिटी', hindiMeaning: 'शहर', emoji: '🏙️' },
  { id: 'w110', englishWord: 'Village', hindiTransliteration: 'विलेज', hindiMeaning: 'गाँव', emoji: '🛖' }
];
